# Generated by Django 5.0.6 on 2024-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(unique=True, verbose_name='Location ID')),
                ('applicant', models.CharField(max_length=300, verbose_name='Applicant')),
                ('facility_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Facility Type')),
                ('location_description', models.CharField(blank=True, max_length=450, null=True, verbose_name='Location Description')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('permit', models.CharField(max_length=25, verbose_name='Permit')),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
                ('food_items', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Food Items')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Food Truck',
                'verbose_name_plural': 'Food Trucks',
                'db_table': 'food_trucks',
            },
        ),
    ]
